In [2]:
# Exercise 09: Missing Mail

import pandas as pd

data = {
  'street': [
    '5230 Newell Road',
    '1381 9th Avenue',
    '1709 Broderick St',
    '2640 Steiner St',
    '2601 Lyon St',
    '1600 Amphitheatre Parkway',
    '7500 N Glenoaks Boulevard',
    '4501 Glencoe Avenue',
    '232 Santa Margarita Ave',
    '471 Emerson Street'
  ],
  'city': [
    'Palo Alto',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'Mountain View',
    'Burbank',
    'Marina del Rey',
    'Menlo Park',
    None
  ],
  'state': [
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    None,
    None
  ],
  'zip_code': [
    94303,
    94122,
    94115,
    94123,
    94123,
    94043,
    91504,
    90292,
    94025,
    None
  ],
  'delivery_type': [
    'First Class',
    'Standard',
    'Priority',
    'Standard',
    None,
    'Expresss',
    'Standard',
    'Standard',
    None,
    None
  ]
}

addresses = pd.DataFrame(data)

addresses

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
4               2601 Lyon St   San Francisco    CA   94123.0           NaN
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard
8    232 Santa Margarita Ave      Menlo Park   NaN   94025.0           NaN
9         471 Emerson Street             NaN   NaN       NaN           NaN

In [3]:
# Remove rows with missing data in any column
cleaned_df = addresses.dropna()
cleaned_df

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard

In [4]:
# Remove rows with missing data in only the 'city' column
city_cleaned_df = addresses.dropna(subset=['city'])
city_cleaned_df

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
4               2601 Lyon St   San Francisco    CA   94123.0           NaN
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard
8    232 Santa Margarita Ave      Menlo Park   NaN   94025.0           NaN

In [6]:
# Impute the missing zip_code with the average
mean_zip_code = addresses['zip_code'].mean()
addresses['zip_code'] = addresses['zip_code'].fillna(mean_zip_code) 
addresses

                      street            city state      zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA  94303.000000   First Class
1            1381 9th Avenue   San Francisco    CA  94122.000000      Standard
2          1709 Broderick St   San Francisco    CA  94115.000000      Priority
3            2640 Steiner St   San Francisco    CA  94123.000000      Standard
4               2601 Lyon St   San Francisco    CA  94123.000000           NaN
5  1600 Amphitheatre Parkway   Mountain View    CA  94043.000000      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA  91504.000000      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA  90292.000000      Standard
8    232 Santa Margarita Ave      Menlo Park   NaN  94025.000000           NaN
9         471 Emerson Street             NaN   NaN  93405.555556           NaN

In [7]:
# Impute missing state and delivery_type values with the most common values
common_state = addresses['state'].mode()[0]
common_delivery_type = addresses['delivery_type'].mode()[0]
addresses['state'] = addresses['state'].fillna(common_state)
addresses['delivery_type'] = addresses['delivery_type'].fillna(common_delivery_type)
addresses

                      street            city state      zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA  94303.000000   First Class
1            1381 9th Avenue   San Francisco    CA  94122.000000      Standard
2          1709 Broderick St   San Francisco    CA  94115.000000      Priority
3            2640 Steiner St   San Francisco    CA  94123.000000      Standard
4               2601 Lyon St   San Francisco    CA  94123.000000      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA  94043.000000      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA  91504.000000      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA  90292.000000      Standard
8    232 Santa Margarita Ave      Menlo Park    CA  94025.000000      Standard
9         471 Emerson Street             NaN    CA  93405.555556      Standard