In [5]:
# Exercise 10: Double Booking

import pandas as pd

data = {
  'ticket_id': [
    'TKT-88421', 'TKT-88421', 'TKT-99213',
    'TKT-55310', 'TKT-55310', 'TKT-66772',
    'TKT-11890', 'TKT-11890', 'TKT-77445', 
    'TKT-33109', 'TKT-18479', 'TKT-90002'
  ],
  'passenger_name': [
    'Don Draper', 'Don Draper', 'Emily Davis',
    'Roger Sterling', 'Roger Sterling', 'Harper Stern',
    'Pete Campbell', 'Pete Campbell', 'Robert Spearing', 
    'Olivia Martinez', 'Andrew Largeman', 'Kendall Roy'
  ],
  'flight': [
    'PA102', 'PA102', 'DL404',
    'UA220', 'UA220', 'UA178',
    'AA778', 'AA778', 'BA305', 
    'DL909', 'UA347', 'PRV-JET'
  ],
  'route': [
    'LGW → LAX', 'LGA → LAX', 'ATL → SEA',
    'JFK → CDG', 'JFK → CDG', 'JFK → LHR',
    'MCI → LGA', 'MCI → LGA', 'LHR → SFO', 
    'DEN → PHX', 'LAX → EWR', 'NYC → Oslo'
  ]
}

tickets = pd.DataFrame(data)

tickets

    ticket_id   passenger_name   flight       route
0   TKT-88421       Don Draper    PA102   LGW → LAX
1   TKT-88421       Don Draper    PA102   LGA → LAX
2   TKT-99213      Emily Davis    DL404   ATL → SEA
3   TKT-55310   Roger Sterling    UA220   JFK → CDG
4   TKT-55310   Roger Sterling    UA220   JFK → CDG
5   TKT-66772     Harper Stern    UA178   JFK → LHR
6   TKT-11890    Pete Campbell    AA778   MCI → LGA
7   TKT-11890    Pete Campbell    AA778   MCI → LGA
8   TKT-77445  Robert Spearing    BA305   LHR → SFO
9   TKT-33109  Olivia Martinez    DL909   DEN → PHX
10  TKT-18479  Andrew Largeman    UA347   LAX → EWR
11  TKT-90002      Kendall Roy  PRV-JET  NYC → Oslo

In [ ]:
# Checking for duplicates
tickets.duplicated()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7      True
8     False
9     False
10    False
11    False
dtype: bool

In [7]:
# Exact duplicate rows
tickets[tickets.duplicated()]

   ticket_id  passenger_name flight      route
4  TKT-55310  Roger Sterling  UA220  JFK → CDG
7  TKT-11890   Pete Campbell  AA778  MCI → LGA

In [9]:
unique_tickets = tickets.drop_duplicates()
unique_tickets

    ticket_id   passenger_name   flight       route
0   TKT-88421       Don Draper    PA102   LGW → LAX
1   TKT-88421       Don Draper    PA102   LGA → LAX
2   TKT-99213      Emily Davis    DL404   ATL → SEA
3   TKT-55310   Roger Sterling    UA220   JFK → CDG
5   TKT-66772     Harper Stern    UA178   JFK → LHR
6   TKT-11890    Pete Campbell    AA778   MCI → LGA
8   TKT-77445  Robert Spearing    BA305   LHR → SFO
9   TKT-33109  Olivia Martinez    DL909   DEN → PHX
10  TKT-18479  Andrew Largeman    UA347   LAX → EWR
11  TKT-90002      Kendall Roy  PRV-JET  NYC → Oslo

In [ ]:
# Still duplicate rows exits (row 0 and row 1) because drop_duplicate() is applied to exact identical rows only
# So we use a subset parameter
unique_tickets = tickets.drop_duplicates(subset=['ticket_id'])
unique_tickets

    ticket_id   passenger_name   flight       route
0   TKT-88421       Don Draper    PA102   LGW → LAX
2   TKT-99213      Emily Davis    DL404   ATL → SEA
3   TKT-55310   Roger Sterling    UA220   JFK → CDG
5   TKT-66772     Harper Stern    UA178   JFK → LHR
6   TKT-11890    Pete Campbell    AA778   MCI → LGA
8   TKT-77445  Robert Spearing    BA305   LHR → SFO
9   TKT-33109  Olivia Martinez    DL909   DEN → PHX
10  TKT-18479  Andrew Largeman    UA347   LAX → EWR
11  TKT-90002      Kendall Roy  PRV-JET  NYC → Oslo