In [ ]:
# Exercise 11: Something's Fishy...

import pandas as pd

# Player's high scores in an online game
data = {
  'player_name': [
    'Parzival', 'Ar3mis', 'Aech', 'Kirito', 'Azuna',
    'nakedinthewoods', 'Sonny666', 'X.X', 'Fendi_Gucci', 'Professor Chaos'
  ],
  'score': [
    '1500', '2300', '1800', '2,100', '1700',
    '2000', '2200', '1600', '1900', '2k50'
  ],
  'level': [
    12, 15, 13, 14, 12, 
    13, 15, 11, 14, 13
  ],
  'time_solved': [
    '23.5', '35.2', '19.0', '14.8', '3.8',
    '42.5', '5h', '33.2', '4.3', '24.6'
  ]
}

high_scores = pd.DataFrame(data)
high_scores

       player_name  score  level time_solved
0         Parzival   1500     12        23.5
1           Ar3mis   2300     15        35.2
2             Aech   1800     13        19.0
3           Kirito  2,100     14        14.8
4            Azuna   1700     12         3.8
5  nakedinthewoods   2000     13        42.5
6         Sonny666   2200     15          5h
7              X.X   1600     11        33.2
8      Fendi_Gucci   1900     14         4.3
9  Professor Chaos   2k50     13        24.6

In [2]:
high_scores.dtypes

player_name      str
score            str
level          int64
time_solved      str
dtype: object

In [5]:
high_scores['score'] = pd.to_numeric(high_scores['score'], errors='coerce')
high_scores['time_solved'] = pd.to_numeric(high_scores['time_solved'], errors='coerce')
high_scores.dtypes

player_name        str
score          float64
level            int64
time_solved    float64
dtype: object

In [7]:
mean_score = high_scores['score'].mean()
mean_time = high_scores['time_solved'].mean()
high_scores['score'] = high_scores['score'].fillna(mean_score)
high_scores['time_solved'] = high_scores['time_solved'].fillna(mean_score)
high_scores

       player_name   score  level  time_solved
0         Parzival  1500.0     12         23.5
1           Ar3mis  2300.0     15         35.2
2             Aech  1800.0     13         19.0
3           Kirito  1875.0     14         14.8
4            Azuna  1700.0     12          3.8
5  nakedinthewoods  2000.0     13         42.5
6         Sonny666  2200.0     15       1875.0
7              X.X  1600.0     11         33.2
8      Fendi_Gucci  1900.0     14          4.3
9  Professor Chaos  1875.0     13         24.6