In [1]:
# Exercise 12: Partiful Responses

import pandas as pd
import random

random.seed(1)

# Different possible RSVP variants
options = ['Yes', 'yes', 'yesss', 'Yep   ', ' yes', 'YES', 'y', 'No  ', 'no', 'N ', 'n', 'no thx']

one_hundred_responses = random.choices(options, k=100)

# Generate fake names for the 100 guests
names = [f'Guest_{i+1}' for i in range(100)]

# Create the DataFrame
responses = pd.DataFrame({
  'name': names,
  'rsvp': one_hundred_responses
})
responses

         name    rsvp
0     Guest_1     yes
1     Guest_2       n
2     Guest_3      N
3     Guest_4  Yep
4     Guest_5     YES
..        ...     ...
95   Guest_96      no
96   Guest_97      N
97   Guest_98       y
98   Guest_99       y
99  Guest_100     YES

[100 rows x 2 columns]

In [ ]:
# Standardize the capitalization
responses['rsvp'] = responses['rsvp'].str.lower()

# Strip extra spaces
responses['rsvp'] = responses['rsvp'].str.strip()

# Replace 'yes' and 'no' to 'y' and 'n' resp.
responses['rsvp'] = responses['rsvp'].str.replace('yes', 'y')
responses['rsvp'] = responses['rsvp'].str.replace('no', 'n')

responses

         name rsvp
0     Guest_1    y
1     Guest_2    n
2     Guest_3    n
3     Guest_4  yep
4     Guest_5    y
..        ...  ...
95   Guest_96    n
96   Guest_97    n
97   Guest_98    y
98   Guest_99    y
99  Guest_100    y

[100 rows x 2 columns]