In [30]:
# Exercise 13: The Final Scrub

import pandas as pd
import numpy as np

patients = pd.DataFrame({
  'patient_id': [
    'PT-2001', 'PT-2001', 'PT-2002', 'PT-2003', 
    'PT-2004', 'PT-2005', 'PT-2006', 'PT-2006', 
    'PT-2007', 'PT-2008', 'PT-2009', 'PT-2010', 
    'PT-2011'
  ],
  'name': [
    'Anthony Ramirez', 'anthony ramirez', 'Grace Mitchell', 'Daniel Brooks', 
    'Nina Patel', 'Marcus Johnson', 'Elena Cruz', 'elena cruz', 
    'William Carter', 'Sophia Nguyen', None, 'Sophia Nguyen', 
    'Ethan Walker'
  ],
  'age': [
    '52', '52', 34, '28', 
    '61', 47, '26', 26, 
    '73', '39', 44, '39', 
    '58'
  ],
  'department': [
    'ER', 'er', 'Trauma', 'ER', 
    'Cardiology', 'Trauma', 'ER', 'er', 
    'ICU', 'ER', 'ER', 'ER', 
    'ICU'
  ],
  'triage_level': [
    'Critical', 'critical', 'Moderate', 'HIGH', 
    'Low', 'Moderate', 'critical', 'CRITICAL', 
    'High', 'Low', 'Moderate', 'low', 
    None
  ],
  'wait_time_minutes': [
    '12', '12', 55, '40 mins', 
    140, 60, '8', 8, 
    '95', '25', None, '25', 
    '70'
  ],
  'admitted': [
    True, True, False, True, 
    True, False, True, True, 
    False, True, False, True, 
    None
  ]
})

patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,PT-2001,Anthony Ramirez,52,ER,Critical,12,True
1,PT-2001,anthony ramirez,52,er,critical,12,True
2,PT-2002,Grace Mitchell,34,Trauma,Moderate,55,False
3,PT-2003,Daniel Brooks,28,ER,HIGH,40 mins,True
4,PT-2004,Nina Patel,61,Cardiology,Low,140,True
5,PT-2005,Marcus Johnson,47,Trauma,Moderate,60,False
6,PT-2006,Elena Cruz,26,ER,critical,8,True
7,PT-2006,elena cruz,26,er,CRITICAL,8,True
8,PT-2007,William Carter,73,ICU,High,95,False
9,PT-2008,Sophia Nguyen,39,ER,Low,25,True
10,PT-2009,NaN,44,ER,Moderate,None,False
11,PT-2010,Sophia Nguyen,39,ER,low,25,True
12,PT-2011,Ethan Walker,58,ICU,NaN,70,None

In [31]:
patients.dtypes

# Normalize text fields
patients['name'] = patients['name'].str.title()
patients['triage_level'] = patients['triage_level'].str.upper()
patients['department'] = patients['department'].str.upper()

# Convert numeric fields
patients['age'] = pd.to_numeric(patients['age'], errors='coerce')
patients['wait_time_minutes'] = (
    patients['wait_time_minutes']
    .astype(str)
    .str.replace(r'[^0-9]', '', regex=True)  # remove non-numeric
    .replace('', np.nan)                     # empty → NaN
    .astype(float)
)

# Remove duplicate records
patients = patients.drop_duplicates()

# Handle missing values
patients['name'] = patients['name'].fillna('Unknown')
patients['triage_level'] = patients['triage_level'].fillna('UNSPECIFIED')
patients['wait_time_minutes'] = patients['wait_time_minutes'].fillna(patients['wait_time_minutes'].median())
patients['admitted'] = patients['admitted'].fillna(False)

patients

,patient_id,name,age,department,triage_level,wait_time_minutes,admitted
0,PT-2001,Anthony Ramirez,52,ER,CRITICAL,12.0,True
2,PT-2002,Grace Mitchell,34,TRAUMA,MODERATE,55.0,False
3,PT-2003,Daniel Brooks,28,ER,HIGH,40.0,True
4,PT-2004,Nina Patel,61,CARDIOLOGY,LOW,140.0,True
5,PT-2005,Marcus Johnson,47,TRAUMA,MODERATE,60.0,False
6,PT-2006,Elena Cruz,26,ER,CRITICAL,8.0,True
8,PT-2007,William Carter,73,ICU,HIGH,95.0,False
9,PT-2008,Sophia Nguyen,39,ER,LOW,25.0,True
10,PT-2009,Unknown,44,ER,MODERATE,47.5,False
11,PT-2010,Sophia Nguyen,39,ER,LOW,25.0,True
12,PT-2011,Ethan Walker,58,ICU,UNSPECIFIED,70.0,False