In [1]:
# Exercise 04: Dungeons & Dragons I

import pandas as pd

# D&D characters data
characters_data = {
  'name': ['Thorne', 'Elira', 'Glim', 'Brug', 'Nyx', 'Kael', 'Mira', 'Drogan', 'Zara', 'Fenwick'],
  'race': ['Elf', 'Human', 'Gnome', 'Half-Orc', 'Tiefling', 'Dragonborn', 'Halfling', 'Dwarf', 'Aasimar', 'Goblin'],
  'class': ['Ranger', 'Cleric', 'Wizard', 'Barbarian', 'Rogue', 'Paladin', 'Bard', 'Fighter', 'Sorcerer', 'Warlock'],
  'level': [5, 3, 4, 2, 6, 7, 3, 5, 4, 2],
  'hp': [42, 28, 33, 25, 48, 56, 30, 44, 36, 24],
  'alignment': [
    'Chaotic Good', 'Lawful Good', 'Neutral', 'Chaotic Neutral', 'Chaotic Evil',
    'Lawful Neutral', 'Neutral Good', 'Neutral', 'Chaotic Good', 'Lawful Evil'
  ]
}

# Create the DataFrame
characters = pd.DataFrame(characters_data)
characters

      name        race      class  level  hp        alignment
0   Thorne         Elf     Ranger      5  42     Chaotic Good
1    Elira       Human     Cleric      3  28      Lawful Good
2     Glim       Gnome     Wizard      4  33          Neutral
3     Brug    Half-Orc  Barbarian      2  25  Chaotic Neutral
4      Nyx    Tiefling      Rogue      6  48     Chaotic Evil
5     Kael  Dragonborn    Paladin      7  56   Lawful Neutral
6     Mira    Halfling       Bard      3  30     Neutral Good
7   Drogan       Dwarf    Fighter      5  44          Neutral
8     Zara     Aasimar   Sorcerer      4  36     Chaotic Good
9  Fenwick      Goblin    Warlock      2  24      Lawful Evil

In [2]:
# Selecting only the 'name' column
character_names = characters['name']
character_names

0     Thorne
1      Elira
2       Glim
3       Brug
4        Nyx
5       Kael
6       Mira
7     Drogan
8       Zara
9    Fenwick
Name: name, dtype: str

In [3]:
# Type of character_names using type()
type(character_names)

pandas.Series

In [4]:
# Selecting multiple columns
basic_stats = characters[['name', 'level', 'hp']]
basic_stats

      name  level  hp
0   Thorne      5  42
1    Elira      3  28
2     Glim      4  33
3     Brug      2  25
4      Nyx      6  48
5     Kael      7  56
6     Mira      3  30
7   Drogan      5  44
8     Zara      4  36
9  Fenwick      2  24

In [5]:
# Selecting all columns except 'alignment'
removed_alignment = characters.drop('alignment', axis=1)
removed_alignment

      name        race      class  level  hp
0   Thorne         Elf     Ranger      5  42
1    Elira       Human     Cleric      3  28
2     Glim       Gnome     Wizard      4  33
3     Brug    Half-Orc  Barbarian      2  25
4      Nyx    Tiefling      Rogue      6  48
5     Kael  Dragonborn    Paladin      7  56
6     Mira    Halfling       Bard      3  30
7   Drogan       Dwarf    Fighter      5  44
8     Zara     Aasimar   Sorcerer      4  36
9  Fenwick      Goblin    Warlock      2  24